import {  Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

import Navber from "@/Component/Navber";
import Footer from "@/Component/Footer";
import { ToastContainer } from "react-toastify";

const roboto = Roboto({
  subsets: ["latin"],
    weight: ["300", "400", "500", "700", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.className} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber></Navber>
      {children}
      <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}
